# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test

on:
  pull_request:
    branches:
      - develop
      - master
    
  push:
    branches:
      - master
      - feature/simplify-DPOIndicator
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: xvfb-run mvn -B package
    # Run BD Scan
    - name: Synopsys Detect Rescan
      run: >  
        curl -s -L https://raw.github.com/blackducksoftware/detect_rescan/dev/detect_rescan.sh > detect_rescan.sh;
        bash detect_rescan.sh --blackduck.url=${{ secrets.BLACKDUCK_URL }} --blackduck.api.token=${{ secrets.BLACKDUCK_API_TOKEN }} --detect.project.name=ta4j --detect.project.version.name=1.0.0 --detect.maven.build.command='package -DskipTests' --testxml
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: '**/policies.xml'
        github_token: ${{ secrets.BD_TOKEN }}
